[#171728280] Generate client SDK and publish to NPM
pagopa/io-functions-bonusapi pull request #30
Opened 2021-01-26 17:30 UTC by gquadrati

Updated `deploy-pipelines.yml` to generate client SDK and publish it to NPM repo.
Version will be aligned with main package.json version, and it will be deployed under two different conditions: 
- major release
- patch release

2021-01-26 20:33 UTC, gunzip reviewed
great ! I just suggest to squash commits doing a rebase :-)

2021-01-26 20:33 UTC, gunzip commented on .devops/deploy-pipelines.yml
> +  deploySDK: $[ or( eq('${{ parameters.RELEASE_SEMVER }}', 'major'), eq('${{ parameters.RELEASE_SEMVER }}', 'patch') )]
why exclude minor?

2021-01-26 20:33 UTC, gunzip commented on .devops/deploy-pipelines.yml
> +              flattenFolders: true
can we make a template (or custom task) for these steps in order to easily share them between projects?

2021-01-26 20:33 UTC, gunzip commented on .devops/deploy-pipelines.yml
> +              cd generated/sdk && yarn build
it looks like yaen build is already called beforewards

2021-01-26 21:04 UTC, gquadrati commented
> great ! I just suggest to squash commits doing a rebase :-)

@gunzip thanks, good to know I will definitely do it next time, sorry :)

2021-01-26 21:07 UTC, gquadrati commented on .devops/deploy-pipelines.yml
> +              flattenFolders: true
yes, absolutely, I just wanted to give it a try before refactoring, but I can start moving this block outside the `deploy-pipelines.yml` file

2021-01-26 21:08 UTC, gquadrati commented on .devops/deploy-pipelines.yml
> +              cd generated/sdk && yarn build
ops, I'll fix it asap

2021-01-26 21:12 UTC, gquadrati commented on .devops/deploy-pipelines.yml
> +  deploySDK: $[ or( eq('${{ parameters.RELEASE_SEMVER }}', 'major'), eq('${{ parameters.RELEASE_SEMVER }}', 'patch') )]
actually I don't really know, I read [this](https://docs.google.com/document/d/1sbPBQTmiM-u6171W72ej5bdiFUJJ-tEeCjQB03UCTzA/edit#heading=h.7xf7hlo11pdp) but I probably understood it wrong..

2021-01-26 21:25 UTC, gunzip commented on .devops/deploy-pipelines.yml
> +  deploySDK: $[ or( eq('${{ parameters.RELEASE_SEMVER }}', 'major'), eq('${{ parameters.RELEASE_SEMVER }}', 'patch') )]
it looks like we should skip patch and generate the SDK on major / minor changes

2021-01-26 23:47 UTC, balanza commented on .devops/deploy-pipelines.yml
> +  deploySDK: $[ or( eq('${{ parameters.RELEASE_SEMVER }}', 'major'), eq('${{ parameters.RELEASE_SEMVER }}', 'patch') )]
I suggest we publish a package at every deploy: the benefit of avoiding useless publications is way less than the risk of having something important skipped by error.

If we want to optimise package generation, we should look at what actually affects the build:
* a change in the specification file, or
* an update on the package `@pagopa/openapi-codegen-ts`

Changes on both can be verified with a couple of bash command (with the first being way easier than the second). 

Anyway, I'd consider this an optimisation and I'd keep it simple for now

2021-01-27 08:32 UTC, gquadrati commented on .devops/deploy-pipelines.yml
> +  deploySDK: $[ or( eq('${{ parameters.RELEASE_SEMVER }}', 'major'), eq('${{ parameters.RELEASE_SEMVER }}', 'patch') )]
I though a change on the spec file would result in a major release. For now I just changed to always deploy the package.

2021-01-27 11:19 UTC, balanza commented on .devops/deploy-pipelines.yml
> +  deploySDK: $[ or( eq('${{ parameters.RELEASE_SEMVER }}', 'major'), eq('${{ parameters.RELEASE_SEMVER }}', 'patch') )]
The point is that here "version" refers to the application, and the spec follows.
In a ideal world the following happens:
* a `patch` version is meant not to ship any changes to the final use (the consumer of the api), thus not to change the specification.
* a `minor` version is meant to ship something to the consumer, hence a change in the specification is expected
* `major` is like `minor`, but changes are breaking ones

This would lead to some edge cases:
* what if we update `openapi-codegen-ts`? The api exposed isn't changed, but the package would.
* what if we improve the _description_ field inside the specification? The api exposed isn't changed, but the package would.

Hence the reason for always publishing.

2021-01-27 13:35 UTC, balanza requested changes

2021-01-27 13:35 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +   dependsOn: ['${{parameters.dependsOnStageName}}']
So it's working?

2021-01-27 13:35 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +  - name: 'dependsOnStageName'
what if we call this parameter `dependsOn`, thus we mimic what stages already do?

2021-01-27 13:35 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +  - name: 'deploySDK'
I'd rather not have this flag: we either run the template or not. If we need this option, we might perform the check in the pipeline

2021-01-27 13:35 UTC, balanza commented on .devops/deploy-pipelines.yml
> +  isBranchMaster: $[ eq(variables['Build.SourceBranch'], 'refs/heads/master') ]
I think this is not used

2021-01-27 14:20 UTC, gquadrati commented on .devops/azure-templates/deploy-client-sdk.yml
> +   dependsOn: ['${{parameters.dependsOnStageName}}']
Yes

2021-01-27 14:21 UTC, gquadrati commented on .devops/azure-templates/deploy-client-sdk.yml
> +  - name: 'dependsOnStageName'
Fine for me, I thought it might be confusing

2021-01-27 14:22 UTC, gquadrati commented on .devops/azure-templates/deploy-client-sdk.yml
> +  - name: 'deploySDK'
ok

2021-01-27 14:41 UTC, gquadrati commented on .devops/deploy-pipelines.yml
> +  isBranchMaster: $[ eq(variables['Build.SourceBranch'], 'refs/heads/master') ]
right

2021-01-27 17:30 UTC, gquadrati commented on .devops/deploy-pipelines.yml
> +  deploySDK: $[ or( eq('${{ parameters.RELEASE_SEMVER }}', 'major'), eq('${{ parameters.RELEASE_SEMVER }}', 'patch') )]
I completely agree 👍

2021-01-28 09:36 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +   dependsOn: ['${{parameters.dependsOnStageName}}']
🚀

2021-01-28 10:04 UTC, gquadrati commented
@balanza we need to merge it in order to test the pipeline.

2021-01-28 10:31 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +    generatedCodeDir: '${{ parameters.projectDir }}/generated/sdk'
Maybe we can try `Agent.TempDirectory` for generated files? https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables-devops-services

```suggestion
    generatedCodeDir: '$(Agent.TempDirectory)/generated'
```

2021-01-28 10:31 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +              cd ${{variables.generatedCodeDir}} && yarn build
I think you don't need this cd as you changed directory in the previous step. For easy troubleshooting, I suggest to have 3 steps:
1. change directory
2. install
3. build

2021-01-28 10:31 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +    default: 'No_Name'
We can try to improve this a little by passing an array instead of a single stage, so that we can have more flexibility for the user and mirror perfectly the actual stage behaviour. We can have `[]` as default value. 
Usage would be
```yaml
  - template: azure-templates/deploy-client-sdk.yml
    parameters:
      dependsOn: 
       - Release
```

Try:
```suggestion
  - name: 'dependsOn'
    type: string
    default: []
```

2021-01-28 10:50 UTC, gquadrati commented on .devops/azure-templates/deploy-client-sdk.yml
> +              cd ${{variables.generatedCodeDir}} && yarn build
I tried.. I don't know what I'm doing wrong but at each script I start again from root folder, like as we open a new terminal.

2021-01-28 11:26 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +              cd ${{variables.generatedCodeDir}} && yarn build
I had different experiences, but it makes sense as each bash scripts acts on its own context. We'll need to investigate more

2021-01-28 12:14 UTC, gquadrati commented on .devops/azure-templates/deploy-client-sdk.yml
> +    default: 'No_Name'
done

2021-01-28 12:25 UTC, balanza commented on .devops/test-deploy-setup-client-sdk.yml
> +      dependsOn: [Release]
I may miss something on yaml syntax, but shouldn't it be

```suggestion
      dependsOn:
        - Release
```

?

2021-01-28 12:31 UTC, gquadrati commented on .devops/test-deploy-setup-client-sdk.yml
> +      dependsOn: [Release]
Maybe we can use both, don't know.. [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml) it says ` dependsOn: string | [ string ]` and to be sure I made a small test [here](https://dev.azure.com/pagopa-io/io-functions-test-deploy/_build/results?buildId=9834&view=results) with two dependencies

2021-01-28 17:38 UTC, gquadrati commented
@balanza  do you think is mature enough to do a test? I could split the publish from the generation and start by checking the artifact

2021-01-28 17:48 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +      value: '$(Agent.TempDirectory)/generated'
Are you sure this works? I guess variables cannot be defined inside a template nor inside a stage.

2021-01-28 17:50 UTC, balanza commented on .devops/azure-templates/deploy-client-sdk.yml
> +      value: '$(Agent.TempDirectory)/generated'
if we need variables local to a job, we can use the syntax you find [here](https://github.com/pagopa/azure-pipeline-templates/blob/master/templates/node-github-release/template.yaml#L54)

2021-01-29 10:04 UTC, gquadrati commented on .devops/azure-templates/deploy-client-sdk.yml
> +      value: '$(Agent.TempDirectory)/generated'
done

2021-02-01 16:52 UTC, balanza reviewed
Should we wait for https://github.com/pagopa/azure-pipeline-templates/pull/11?

2021-02-01 17:04 UTC, gquadrati commented on .devops/azure-templates/deploy-client-sdk.yml
> +             echo "##vso[task.setvariable variable=codegenPackageNameParameter]$PKG_NAME_PARAM"
> Should we wait for [pagopa/azure-pipeline-templates#11](https://github.com/pagopa/azure-pipeline-templates/pull/11)?

Fine for me, I'm updating it.

2021-02-05 09:12 UTC, balanza requested changes

2021-02-05 09:12 UTC, balanza commented on .devops/deploy-pipelines.yml
> +          displayName: 'Start verdaccio'
why this?

2021-02-05 09:12 UTC, balanza commented on .devops/test-deploy-setup-client-sdk.yml
Do we still need a test pipeline here?

2021-02-05 09:14 UTC, gquadrati commented on .devops/test-deploy-setup-client-sdk.yml
No, actually I was about to move to a completely new branch and then we can delete this one.

2021-02-16 12:46 UTC, closed without merging